spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:portfoliodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

# Configuración de Email (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alonso.b.millar@gmail.com
# IMPORTANTE: Aquí debes usar una 'App Password' de Google
# Consíguela en: https://myaccount.google.com/apppasswords
spring.mail.password=npqbgdhartdlmctu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
